version: '2.1'

services:
    bref-web:
        image: bref/fpm-dev-gateway
        ports:
            - "9980:80"
        volumes:
            - .:/var/task
        #      - ./setup/nginx/bref.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        environment:
            HANDLER: public/index.php
            DOCUMENT_ROOT: public

    php:
        container_name: magma_glass_php
        image: magma-glass-php
        build:
            context: .
            dockerfile: setup/php/Dockerfile
        volumes:
            - ./:/var/task
            - /tmp/var-cache:/var/task/cache
            - /run/media/axel/DATA/LinuxData/home/axel/.config/obsidian/Obsidian Help:/var/task/storage/notes
        user: "1000:1000"

    redis:
        image: redis
        container_name: magma_glass_redis
        ports:
            - "6378:6379"
        depends_on:
            - php
